### ISSUE TITLE
place variable in for loop

### ISSUE THREAD

**Issue by babadoo** [newville/asteval#14]
there is an issue with using a variable named "place" in a for loop:

from asteval import Interpreter
code = "for place in [1,2,3]: pass"
interpr = Interpreter()
interpr.eval(code)

'str' object cannot be interpreted as an integer

There is a place item in the "FROM_NUMPY" set in asteval, maybe there is some collision.

**Comment by newville** [comment]
@babadoo  Thanks!   Sorry for the cryptic error message, which was due completely to my mistake.  It should be OK to use a variable name that also happens to be in the largish set of things imported from numpy.  Of course, you wouldn't be able to use `place`, but it should work.  

The error was that we also need to be careful that when such a replacement does occur, that the process of pickling an expression can also work.  The mistake was there -- popping from a list (which needs an index) when I should have been removing (which needs an element, in this case the string of 'place').   

Fixed in git (37be5b2f6bb88938eb2b74b5881d6d00c4307c3f).

 
removing from a
