### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by fabaff** [newville/asteval#69]
The Fedora package of asteval fails to build with Python 3.9.0a5. There are now tests which are no longer passing.

Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1819177

**Comment by newville** [comment]
@fabaff  Thanks for the report.  I cannot tell exactly what the problem is, but it looks like it has something to do with getting an item from a dict or sequence.   

I have not looked at Python 3.9 at all (or alpha versions in general). If history is a useful guide, each minor version may introduce a slight change in the AST definition that is usually not too hard to accommodate.
If you or anyone else has an idea of what changed or is causing this, please let me know!

**Comment by newville** [comment]
@fabaff  `asteval` version 0.9.19 works for me with Python 3.9beta3 - there were a few different small fixes needed.  I tested only with one machine and only the current testsuite.   I can believe other issues could be found once Py3.9 is released and available on the automated testing services, so I will leave this issue open until we are testing with Py3.9.   But, I also believe that 0.9.19 may very well work just fine.

**Comment by fabaff** [comment]
Thanks. The tests are all successful during the RPM build process now.
