### ISSUE TITLE
Interpreter initialisation is slow when symtable/usersyms contains long lists

### ISSUE THREAD

**Issue by damamaty** [newville/asteval#77]
Because it calls repr(val) for each value and standard containers don't limit the output. 

Example (takes cpl mins to run the initializer):
```
from asteval import Interpreter
a = [1] * 1_000_000_000
Interpreter({"a": a}) 
```

**Comment by newville** [comment]
@damamaty That seems okay to me.  Does "cpl mins"  mean "couple of minutes"?     Anyway, I don't quite see this as a serious problem.

**Comment by damamaty** [comment]
Yes, sorry, "couple minutes". It can take longer depending on the list size.
Reported it because it was a reason of bad performance in our case. Can be avoided by e.g. using wrappers around list/dict with redefined __repr__, but from my point of view it is unexpected that the library does that.

**Comment by newville** [comment]
@damamaty Huh?   What does `__repr__` have to do with it?   Should I know what you expected to happen?  As it turns out, I don't.

Why would anyone create a list with a billion elements and then expose that in a sandboxed interpreter?    
Performance is just not a high priority here, but you may recall that there is this thing called `numpy`.
